new
Aleksey01091993/java-filmorate pull request #1
Opened 2023-08-10 22:43 UTC by Aleksey01091993

запрос на извлечение

2023-08-11 13:20 UTC, YazykovMikhail commented
Давай осознаные названия коммитам и ПР, пиши кратко что было сделано или почему

2023-08-11 13:31 UTC, YazykovMikhail requested changes

2023-08-11 13:31 UTC, YazykovMikhail commented on src/main/java/controller/FilmController.java
> +        if (film.getName().isEmpty()) {
такую валидацию хранить в контроллере не очень.
Или вынеси в отдельынй метод, или сделай валидацию прям в модели с помощью анотаций:

	@NotBlank
	private String name;
	@Size(min = 1, max = 200)
	private String description;
	@NotNull
	private LocalDate releaseDate;
	@Min(1)
	private long duration; // minutes
	
и проставь public Film add(@Validated @RequestBody  Film film) {

2023-08-11 13:31 UTC, YazykovMikhail commented on src/main/java/controller/FilmController.java
> +
Должен быть еще метод update

2023-08-11 13:31 UTC, YazykovMikhail commented on src/main/java/controller/UserController.java
> +
Должен быть еще метод update

2023-08-11 13:31 UTC, YazykovMikhail commented on src/main/java/controller/UserController.java
> +        if (user.getEmail().isEmpty() || !user.getEmail().contains("@")) {
тоже замечание про валидацию

2023-08-11 13:31 UTC, YazykovMikhail commented on src/main/java/controller/FilmController.java
> +    public Film add(@RequestBody Film film) {
нехватает базовых логов, базовые логи:

(Request request) {
// лог.пришел запрос Post /films с телом: request
//бизнес логика
// отправлен ответ с телом: response
}

тогда ьудет поняно что пришло и какой ответ ушел, а между нуими уже логи для бизнес логики или ошибок

2023-08-11 13:31 UTC, YazykovMikhail commented on src/main/java/controller/FilmController.java
> +    @PostMapping(value = "/film")
тут везде путь @PostMapping("/films")
можно вообще вынести над классом анатацию
@RequestMapping(value = "/films")

а над методами убрать

2023-08-11 13:31 UTC, YazykovMikhail commented on src/main/java/controller/FilmController.java
> +    @PostMapping(value = "/film")
тоже касается юзера

2023-08-11 13:31 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +package ru.yandex.practicum.filmorate;
все классы, пакеты должно были создаваться тут, внутри этого пакета.
А не рядом. 
Перенеси все сюда

2023-08-11 13:37 UTC, YazykovMikhail requested changes

2023-08-11 13:37 UTC, YazykovMikhail commented on src/main/java/controller/UserController.java
> +            User user1 = new User(user.getId(), user.getEmail(), user.getLogin(), user.getLogin(),
зачем созадвать нвоого юзера, когда он уже пришел в запросе?
и в запросе id на создание придти не может, ведь id устанавливает само приложение при создании.
поэтому сделай поле 
private long counter = 0L;
и увеличивай его перед установкой в модель и сохраняй модель

2023-08-11 13:37 UTC, YazykovMikhail commented on src/main/java/controller/UserController.java
> +    private Map<String, User> users = new HashMap<>();
final
поправь и в Film

2023-08-11 14:23 UTC, Aleksey01091993 commented on src/main/java/controller/UserController.java
> +
так я специально зделал мапу а не лист чтобы обновленние делалось автоматом

2023-08-11 14:46 UTC, Aleksey01091993 commented on src/main/java/controller/FilmController.java
> +        if (film.getName().isEmpty()) {
@NotBlank private String name; на сколько я понял мы просто обозначаем что переменная не может быть пустая   мы обозначим то как мне кинуть свое исключение?

2023-08-11 14:49 UTC, Aleksey01091993 commented on src/main/java/controller/FilmController.java
> +
HashMap на сколько я помню если ключь одинаковый то он просто заменяет содержимое так у нас и получается ключь есть обновляем ключа нету добовляем

2023-08-11 14:50 UTC, Aleksey01091993 commented on src/main/java/controller/FilmController.java
> +
методы я зделал но смылсла как токового в них нету

2023-08-11 14:51 UTC, Aleksey01091993 commented on src/main/java/controller/FilmController.java
> +        if (film.getName().isEmpty()) {
вынес все в отдельный метод

2023-08-11 14:51 UTC, Aleksey01091993 commented on src/main/java/controller/UserController.java
> +        if (user.getEmail().isEmpty() || !user.getEmail().contains("@")) {
также вынес все в отдельный метод

2023-08-11 14:56 UTC, Aleksey01091993 commented on src/main/java/controller/FilmController.java
> +    public Film add(@RequestBody Film film) {
исправил все в отдельном методе check

2023-08-11 15:13 UTC, Aleksey01091993 commented on src/main/java/controller/FilmController.java
> +    @PostMapping(value = "/film")
у меня разные запросы если films/GET возвращает список всех фильмов а film/POST добавляет и обновляет но насколько я понял ты хочешь что бы я все сделал через один запрос films?

2023-08-11 15:16 UTC, Aleksey01091993 commented on src/main/java/controller/UserController.java
> +    private Map<String, User> users = new HashMap<>();
поправил

2023-08-11 15:53 UTC, Aleksey01091993 commented on src/main/java/controller/FilmController.java
> +        if (film.getName().isEmpty()) {
только если перехватывать то которое выскочит и кидать свое а попроще способ есть?

2023-08-11 16:06 UTC, Aleksey01091993 commented on src/main/java/controller/UserController.java
> +            User user1 = new User(user.getId(), user.getEmail(), user.getLogin(), user.getLogin(),
поправил теперь ид назначается автоматически и все привязано к нему в мапе

2023-08-11 19:09 UTC, YazykovMikhail requested changes

2023-08-11 19:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return check(film);
обрати внимание я в предыдущем ревья я подскзаал вынести валидацию в отдельный метод, а не весь метод. 
Каждый метод должен отвечать за свое.
Этот метод для добавления т.е как должно выгялдить: 

```
@PostMapping
    public Film add(@Validated @RequestBody Film film) {
        check(film);
        final long id = ++counter;
        film.setId(id);
        films.put(film.getId(), film);
        return film;
    }
    
    private void check(Film film) {
        log.info("лог.пришел запрос Post /films с телом: request");
        if (film.getName().isEmpty()) {
            log.debug("название не может быть пустым");
            throw new ValidationException("название не может быть пустым");
        } else if (film.getDescription().length() > 200) {
            log.debug("максимальная длина описания — 200 символов");
            throw new ValidationException("максимальная длина описания — 200 символов");
        } else if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 27))) {
            log.debug("дата релиза — не раньше 28.12.1895");
            throw new ValidationException("дата релиза — не раньше 28.12.1895");
        } else if (film.getDuration().isNegative() || film.getDuration().isZero()) {
            log.debug("продолжительность фильма должна быть положительной");
            throw new ValidationException("продолжительность фильма должна быть положительной");
        }
    }


```

2023-08-11 19:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
private long counter = 0L;

2023-08-11 19:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping()
У тебя два Post запроса по одному пути, какой выбирать? 
Для обновления используется @PutMapping

Логика обноляние отличается от добавления, если этого фильма нет? то ты его добавишь, а нужно было обнвоить
т.е стоит добавить проверку
if (!films.containsKey(film.getId())) {
			throw new ValidationException("Not found key: " + fikm.getId());
		}

2023-08-11 19:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping()
Касается и User

2023-08-11 19:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return check(film);
Касается и User

2023-08-11 19:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
Касается и User

2023-08-11 19:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private static long idFilm = 0;
модель не может отвечать за счетчик идентификатора. То куда ты сохраняешь отвечает за него, сейчас ты хранишь данные в сервисе вот сервис и овтечает, завтра ты будешь зранить данные в базе данных, будет отвечать база. 
Модель только переносит данные

2023-08-11 19:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final long id = ++idFilm;
private long id;

2023-08-11 19:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final long id = ++idFilm;
касается и User

2023-08-11 19:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private static long idFilm = 0;
касается и User

2023-08-11 19:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film add(@Validated @RequestBody Film film) {
Ты добавил @Validated, но аннотация для проверки в модели нет, тогда и @Validated не нужно.

2023-08-12 10:01 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return check(film);
исправил

2023-08-12 10:01 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
исправил

2023-08-12 10:08 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping()
исправил

2023-08-12 10:09 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private static long idFilm = 0;
исправил

2023-08-12 10:09 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final long id = ++idFilm;
исправил

2023-08-12 10:16 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film add(@Validated @RequestBody Film film) {
исправил везде

2023-08-12 13:55 UTC, YazykovMikhail approved these changes

2023-08-12 13:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping()
не все поправил, прочитай внимательно еще раз

2023-08-12 13:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
у тебя по одноу пути два метода с Post как вызвать обновлдение, а не добавление, я написал в предыдущем ревью

2023-08-12 14:05 UTC, YazykovMikhail approved these changes

2023-08-23 17:27 UTC, merged