выполнена половиннаь
Aleksey01091993/java-filmorate pull request #2
Opened 2023-08-24 12:53 UTC by Aleksey01091993

2023-08-25 12:41 UTC, YazykovMikhail requested changes

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage storage;
обращение из контролелра только в Сервис. 
А уже из Сервиса в Сторадж

касается всех

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController() {
@Autowired
	public FilmController(FilmService service) {
		this.service = service;
	}
потоври еще раз как работает @Autowired

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        this.service = new FilmService(new InMemoryFilmStorage());
так делать не нужно. Используй бины и @Autowired
потвори еще раз как работает

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    public List<User> getUsers();
public - писать не обязательно, поумолчанию public

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    public List<User> getUsers();
касается и FilmStorage

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +
не хватает метода 
public User get(long id)

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +
не хватает метода 
public Film get(long id)

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        storage.getUsers().get((int) userId).getFriends().add(friendId);
представь что у тебя база данных на 987654678909 строк, не будешь же ты каждый раз доставать все записи что бы найти одну.
Сделай метод в сторадже get(id) и получай конкретную запись по id

Касается всех методов где нужно достать один обьект, а ты получаешь все и пробегаешься по ним

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getTopFilms(@PathVariable(required = false) String count) {
getTopFilms(@RequestParam(defaultValue = "10" int count) {

думаю ты согласишься что количество лучше принимать в int, чем в строку.

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        int ids = 10;
показал как на уровне контроллера сделать число поумолчанию.

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
Совсем нет логирвоания в контроллерах.
Как я говорил стоит сделать как минимум базовое логирвоание:

лог(Пришел запрос такой то с таким то телом)
//логика метода
лог(Отправлен ответ такой то, с таким то телом)
Касается всех

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          final long id = ++counter;
за это теперь отвечает сторадж, ведь именно там хранятсья обьекты

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private static long counter = 0L;
за это теперь отвечает сторадж, ведь именно там хранятсья обьекты
не нужно делать static, статик озаначает что знаение статично, а у тебя измеянется.

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private static long counter = 0L;
Касается и User

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void addLike(@PathVariable Map<String, String> path) {
@PutMapping("/films/{id}/like/{userId}")
	public void addLike(@PathVariable long id, @PathVariable long userId) {

повтори как работать с @PathVariable 
касатеся и deleteLike

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void addLike(@PathVariable Map<String, String> path) {
касается и User

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @ExceptionHandler
Вынеси в отдельный класс
к примеру:

@RestControllerAdvice
public class ErrorHandler {
	private static final Logger log = LoggerFactory.getLogger(ErrorHandler.class);

	@ExceptionHandler
	@ResponseStatus(HttpStatus.NOT_FOUND)
	public ErrorResponse handleNotFoundException(final DataNotFoundException e) {
		log.info("404 {}", e.getMessage());
		return new ErrorResponse(e.getMessage());
	}

	@ExceptionHandler
	@ResponseStatus(HttpStatus.BAD_REQUEST)
	public ErrorResponse handleValidationException(final ValidationException e) {
		log.error("400 {}", e.getMessage());
		return new ErrorResponse(e.getMessage());
	}

	@ExceptionHandler
	@ResponseStatus(HttpStatus.CONFLICT)
	public ErrorResponse handleAlreadyExistException(final DataAlreadyExistException e) {
		log.info("409 {}", e.getMessage());
		return new ErrorResponse(e.getMessage());
	}

	@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}
}

2023-08-25 12:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private void check (Film film) {
Предлагаю таки еределать на реализацию через аннотации, в обьектах которые приходят в запросе повестить анноатции для фильма например:
	@NotBlank
	private String name;
	@Size(max = 200)
	private String description;
	@NotNull
	private LocalDate releaseDate;
	@Min(1)
	private long duration;
	
и в контроллере 	где нужна валидация проставить @Validated
public Film update(@Validated @RequestBody final Film film) {

это более стандартное решение

2023-08-27 11:23 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    public List<User> getUsers();
выполнен

2023-08-27 11:24 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +
выполнен

2023-08-27 11:24 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          final long id = ++counter;
выполен

2023-08-27 11:33 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private static long counter = 0L;
выполнен

2023-08-28 08:03 UTC, YazykovMikhail reviewed
Коммиты с описанием "[выполнена половиннаь]" делать не очень, стоит давать осмысленные комментари, что бы можно было понять что было сделано в этом комите или почему он был нужен. 

Так же ты сделал ПР с названием [выполнена половиннаь] - это тоже не очень, ведь каждый ПР это мерж в мастер, мержить половины работы в мастер не очень, ведь в мастере хранится актуальный код. И так же в названии тоже стоит указывать что сделал.

2023-08-28 08:03 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        service.update(film);
return service.update(film);
       
  поправь для всех, если метод возврашеь обновелнный/созданным обьект, стоит возвращать именно его

2023-08-28 08:04 UTC, YazykovMikhail commented
И лучше отправять всю работу полностью, а не половину. 
Посмотри новые комментарии и поправь оставшийся

2023-08-28 08:05 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    public List<User> getUsers();
@Aleksey01091993 можно отмечать комментарий "решенным" через интерфейс, и тогда будет лучше видно что еще осталось и что было сделано.

2023-08-28 11:39 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage{
исправил

2023-08-28 11:39 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private static long counter = 0L;
исправил

2023-08-28 12:01 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserStorage getStorage() {
исправил

2023-08-28 12:20 UTC, merged