Add database
Aleksey01091993/java-filmorate pull request #4
Opened 2023-10-02 17:06 UTC by Aleksey01091993

2023-10-02 18:46 UTC, YazykovMikhail requested changes

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +CREATE TABLE PERSONS(
назови лучше USERS
ведь это пользователи

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +);
стоит сделать поле 
    mpa_id      int references MPA(id),
тут, отдельную таблицу MPA_FILM делать не нужно, ведь тут связь один ко многим, а не многие ко многим.

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +mpa VARCHAR
назови 
name
таблица и так наывается MPA

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +);
и так же лучше создавать вот так:

create table if not exists USERS

что бы если таблица уже существует не перетирать, поправь везде

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          log.info("Пришел GET запрос /films с телом: {id}", id);
log.info("Пришел GET запрос /films с телом: {}", id);
  
  вот так и тогда id само подставится вместо {}
  попарвь везде

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Genre getGenre(@PathVariable int id) {
Для Genre нужен свой контролер, это же другой путь без начального 
@RequestMapping(value = "/films")

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/mpa")
Для Mpa нужен свой контролер, это же другой путь без начального 
@RequestMapping(value = "/films")

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private void check(Film film) {
вынеси валидацию в сервис лучше

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
Тоже лучше 
    private void check(User user) {
вынеси в сервис, а то там у тебя уже и бизнес логика, лучше это держать в сервисе

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes;
для лайков есть отдельаня таблица для хранения и отдельныеэндпоинты их можно от сюда убрать

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes;
ну или оставить если ты делаешь обратную соместимость с inmemory
но тогда поставь @JsonIgnore

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends;
тут тоже
@JsonIgnore, если используешь для обратной совестимости

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends;
т.к в текущей реализации для работы с друзьями есть отдельыне эндпоиты и таблица

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        List<Integer> likes = jdbcTemplate.query(
это заполнять не нужно, для работы с лайками есть отдельные эндпоинты

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                "select * from films", this::mapRow
стоит получать сразу все даныне которые моно одним запросом, чем делать несколкьо потом еще.  
		return jdbcTemplate.query("select * from FILMS f, MPA m where f.MPA_ID = m.MPA_ID", DbFilmStorage::makeFilm);

как ты можешь заметить тут нет genre, потому что связь genre и films многие ко многим. 

если ты получишь так: 
select * from films то тебе нужно потом для каждого фильма еще находить все его жанры, это очень много запросов к бд. 
Если сделаешь join по жанрам то вернуться много дубликатов фильмов. поэтому:
тут мы получаем как я показал выше, а уже из сервиса вызываем:

```
@Override
	public List<Film> getAll() {
		final List<Film> films = super.getAll();
		genreStorage.load(films);
		return films;
	}
```

где 

```
public void load(List<Film> films) {
		String inSql = String.join(",", Collections.nCopies(films.size(), "?"));
		final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));
		final String sqlQuery = "select * from GENRES g, FILM_GENRES fg where fg.GENRE_ID = g.GENRE_ID AND fg.FILM_ID in (" + inSql + ")";
		jdbcTemplate.query(sqlQuery, (rs) -> {
			final Film film = filmById.get(rs.getLong("FILM_ID"));
			film.addGenre(makeGenre(rs, 0));
		}, films.stream().map(StorageData::getId).toArray());
	}
```

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +
так же стоит сделать свои storage для:
DbFriendStorage
DbGenreStorage
DbLikesStorage
DbMpaStorage

ведь это таблицы, у каждой таблицы свои сторадж

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        jdbcTemplate.update(
Это будет не нужно, так как связь тут не многие ко многим, а один ко многим. 
Просто обновляй поле в запросе выше

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    public Film getFilm(int id) {
тут по аналогии с GetAll
получаем в запросе сразу все чт оможно, что бы не делать лишние запросы и потом отдельно через сервис импортируем genre

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    public void addLike(int filmId, int userId) {
вот это как раз вынести DbLikesStorage

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                "SELECT COUNT(film_id) FROM likes WHERE like_person_id = ? AND film_id = ?",
это не нужно делать, стоит минимизировать количесвто запросов к д, потому что это тяжелая операция, создается подключение, выполняется запрос, обновляются данные. Это время.

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        isUser = jdbcTemplate.queryForObject(
как ты жуе понял это не нужно запрашивать, сразу удаляй и все
		String sqlQuery = "delete from LIKES where FILM_ID = ? and USER_ID = ?";
		jdbcTemplate.update(sqlQuery, filmId, userId);

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        List<Integer> genre = jdbcTemplate.query("SELECT genre FROM genre_film WHERE film_id = ?",
как мы уже поняли убираем это от сюда

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        SqlRowSet mpa = jdbcTemplate.queryForRowSet("SELECT mpa FROM mpa_film WHERE film_id = ?",
как мы уже поняли убираем это от сюда

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        SqlRowSet mpa = jdbcTemplate.queryForRowSet("SELECT mpa FROM mpa_film WHERE film_id = ?",
в rs уже будет приходит это поле

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    private int counter = 0;
этого делать не нужно, БД сама проставляет идентификаторы

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +    private int counter = 0;
этого делать не нужно, БД сама проставляет идентификаторы

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -    public void addLike(long filmId, long userId) {
стоит в сервисе проверять есть ли пользователь и фильм:

```
public void addLike(long filmId, long userId) {
		final Film film = storage.get(filmId);
		final User user = userStorage.get(userId);
		likesStorage.addLike(film.getId(), user.getId());
	}
	
```

а уже запрос на получение пользователя выглдяит как то так:

```
@Override
	public User get(long id) {
		final String sqlQuery = "select * from USERS where USER_ID = ?";
		final List<User> users = jdbcTemplate.query(sqlQuery, DbUserStorage::makeUser, id);
		if (users.size() != 1) {
			throw new DataNotFoundException("user id=" + id);
		}
		return users.get(0);
	}
```

если не надется будет исключение, аналогично и в фильме.

2023-10-02 18:46 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -    public void addLike(long filmId, long userId) {
в таком стиле стоит сделать и removeLike

2023-10-02 20:59 UTC, Aleksey01091993 commented on src/main/resources/schema.sql
> +);
+

2023-10-02 20:59 UTC, Aleksey01091993 commented on src/main/resources/schema.sql
> +mpa VARCHAR
+

2023-10-02 20:59 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          log.info("Пришел GET запрос /films с телом: {id}", id);
+

2023-10-02 20:59 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Genre getGenre(@PathVariable int id) {
+

2023-10-02 21:00 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/mpa")
+

2023-10-02 21:00 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private void check(Film film) {
+

2023-10-02 21:00 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
+

2023-10-02 21:00 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes;
+

2023-10-02 21:00 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends;
+

2023-10-02 21:01 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        List<Integer> likes = jdbcTemplate.query(
+

2023-10-08 17:23 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        List<Integer> genre = jdbcTemplate.query("SELECT genre FROM genre_film WHERE film_id = ?",
.

2023-10-08 20:49 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                "select * from films", this::mapRow
.

2023-10-08 20:50 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +
.

2023-10-08 21:03 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +
.

2023-10-08 21:03 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        jdbcTemplate.update(
.

2023-10-08 21:04 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    public Film getFilm(int id) {
.

2023-10-08 21:08 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    public Film getFilm(int id) {
.

2023-10-08 21:08 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    public void addLike(int filmId, int userId) {
.

2023-10-08 21:17 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                "SELECT COUNT(film_id) FROM likes WHERE like_person_id = ? AND film_id = ?",
.

2023-10-08 21:17 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        isUser = jdbcTemplate.queryForObject(
.

2023-10-08 21:19 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        SqlRowSet mpa = jdbcTemplate.queryForRowSet("SELECT mpa FROM mpa_film WHERE film_id = ?",
.

2023-10-08 21:21 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    private int counter = 0;
.

2023-10-08 21:21 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +    private int counter = 0;
.

2023-10-09 13:19 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        SqlRowSet mpa = jdbcTemplate.queryForRowSet("SELECT mpa FROM mpa_film WHERE film_id = ?",
.

2023-10-09 13:19 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    private int counter = 0;
.

2023-10-09 13:21 UTC, Aleksey01091993 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -    public void addLike(long filmId, long userId) {
.

2023-10-10 12:49 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          log.info("Пришел GET запрос /films с телом: {id}", id);
Можно нажимать на три точки и делать комментарий "решенным"

2023-10-10 12:53 UTC, YazykovMikhail approved these changes

2023-10-14 14:28 UTC, merged